### ISSUE TITLE
explorer todos

### ISSUE THREAD

**Issue by Phinome** [AElfProject/aelf-block-explorer#1]
- [x] browser common api work
- [x] infoList Component work

- [x] home page

    - aelf transaction price

- [x] block page

- [x] transactions page

**Comment by Phinome** [comment]
- [ ] search is not work

- [ ] blocks detail page is not work

- [ ] transaction detail page is not work

- [ ] address detail page is not work

- [ ] applications page is not work

**Comment by Phinome** [comment]
- [ ] search is not work [pending]

- [ ] blocks detail page is work

- [ ] transaction detail page is work, but some datasource is incorrect.

- [ ] address detail page is not work

- [ ] applications page is not work

**Comment by Phinome** [comment]
- [ ] search is not work [pending]

- [x] blocks detail page is work

- [ ] transaction detail page is work

- [ ] address detail page is work

- [ ] applications page is not work [pending]

- [ ] ELF Trades data & chart is not work.

**Comment by hzz780** [comment]
- [ ] search is not work

- [x] blocks detail page is work

- [x] transaction detail page is work

- [x] address detail page is work

- [ ] applications page is not work [pending]

- [x] ELF Trades data & chart is not work.

    - choose open api to get trade data;
    - solve cors problems
    - code display components
    - combine with home page.

**Comment by hzz780** [comment]
Basic Explorer is well run.

[version-basic-20181119](https://github.com/AElfProject/aelf-block-explorer/tree/version-basic-20181119)
