### ISSUE TITLE
[Explorer] Some issue about aelf-block-explorer

### ISSUE THREAD

**Issue by YueZh127** [AElfProject/aelf-block-explorer#7]
There is some UI issue about explorer, detail as below:

- [x] 1. Change the explorer window, some of the Element display overlaps
![image](https://user-images.githubusercontent.com/45747546/49996481-107e7600-ffca-11e8-906e-e2e4721bff53.png)
![image](https://user-images.githubusercontent.com/45747546/49996657-8d115480-ffca-11e8-84c8-9ceff2c0da79.png)
![image](https://user-images.githubusercontent.com/45747546/49996955-4cfea180-ffcb-11e8-9322-12919f9a5866.png)

- [x] 2.Change the explore window, the search icon on the header search and the  path can not be displayed completely
![image](https://user-images.githubusercontent.com/45747546/49997357-50465d00-ffcc-11e8-9525-c788973f4b8b.png)

- [x] 3.On small window and the  header navbar is opened , expand the explore window , the menu shows incorrect.
![image](https://user-images.githubusercontent.com/45747546/49996941-42440c80-ffcb-11e8-88ab-1d034c42486f.png)

- [ ] 4.On small window, Goto is missing.
![image](https://user-images.githubusercontent.com/45747546/49997000-69024300-ffcb-11e8-9054-3c3c1bb9c96c.png)

- [ ] 5.When the number is too long, it will display out of range
![image](https://user-images.githubusercontent.com/45747546/49997906-ceefca00-ffcd-11e8-87d9-a4287dcf1ab1.png)

**Comment by YueZh127** [comment]
- [ ] 6. The color of Direction does not show clearly
![image](https://user-images.githubusercontent.com/45747546/52933073-03e11a00-338d-11e9-9873-65ae8fd9b2ec.png)

- [ ] 7. The time displayed is too close to the edge of Real time transaction 
![image](https://user-images.githubusercontent.com/45747546/52933527-9f26bf00-338e-11e9-84e6-dcfd91ba6bf9.png)

- [ ] 8. after clicking the space or the option, the menu bar does not close
![image](https://user-images.githubusercontent.com/45747546/52933848-94b8f500-338f-11e9-92ff-fddeca1c9aa9.png)

**Comment by YueZh127** [comment]
- [ ] 9. Account address :Overview is empty
![image](https://user-images.githubusercontent.com/45747546/52934500-94215e00-3391-11e9-936b-dbea6ac64cc1.png)

Contract address: Overview and transactions is empty
![image](https://user-images.githubusercontent.com/45747546/52934505-9edbf300-3391-11e9-93c3-d420565c1485.png)

The quantity in transaction keeps showing 0

**Comment by YueZh127** [comment]
- [ ] 10. Uniform the format of Resource quantity 
![image](https://user-images.githubusercontent.com/45747546/53013118-e9d43400-347f-11e9-873e-b962e58c64d1.png)

**Comment by cat-walk** [comment]
> * [ ]  6. The color of Direction does not show clearly
>   ![image](https://user-images.githubusercontent.com/45747546/52933073-03e11a00-338d-11e9-9873-65ae8fd9b2ec.png)
> * [ ]  7. The time displayed is too close to the edge of Real time transaction
>   ![image](https://user-images.githubusercontent.com/45747546/52933527-9f26bf00-338e-11e9-84e6-dcfd91ba6bf9.png)
> * [ ]  8. after clicking the space or the option, the menu bar does not close
>   ![image](https://user-images.githubusercontent.com/45747546/52933848-94b8f500-338f-11e9-92ff-fddeca1c9aa9.png)

Solved in the lastest version.

**Comment by cat-walk** [comment]
> There is some UI issue about explorer, detail as below:
> * [x]  4.On small window, Goto is missing.
>   ![image](https://user-images.githubusercontent.com/45747546/49997000-69024300-ffcb-11e8-9054-3c3c1bb9c96c.png)
> * [ ]  5.When the number is too long, it will display out of range
>   ![image](https://user-images.githubusercontent.com/45747546/49997906-ceefca00-ffcd-11e8-87d9-a4287dcf1ab1.png)

Solve problem 4. Problem 5 will be handled if the product manager confirm that we need to compatible with  the screen with such length-width ratio.

**Comment by cat-walk** [comment]
> - [ ] Contract address: Overview and transactions is empty
> ![image](https://user-images.githubusercontent.com/45747546/52934505-9edbf300-3391-11e9-93c3-d420565c1485.png)
> 
> The quantity in transaction keeps showing 0

Some of the transaction are empty maybe resulted from that it's unconfirmed block. I'll ask @atom-yang for the detail later.
