### ISSUE TITLE
Excessive http requests require optimization

### ISSUE THREAD

**Issue by bikedawuwang** [AElfProject/aelf-block-explorer#9]
#### Currently, the data is returned from the chain, and the current interface needs to obtain the data from the repeated request interface.
![image](https://user-images.githubusercontent.com/16474060/50966000-98469a00-150e-11e9-87bc-a28d44521a69.png)
as the picture shows
#### The current page load requires 127 requests. If the API interface is used, it will reduce at least 20 requests (most of which are for wallet information, there will be improvements after using the browser plugin)

**Comment by hzz780** [comment]
There is the same problem in Resource System.

I will implement some APIs after i finished beta version of the web extension named NightElf.

**Comment by hzz780** [comment]
17 requests now
